require 'ajaxlibs/constants'
require 'ajaxlibs/exceptions'
require 'ajaxlibs/versions_tools'
require 'ajaxlibs/library'
require 'ajaxlibs/libraries/chrome_frame.rb'
require 'ajaxlibs/libraries/dojo'
require 'ajaxlibs/libraries/ext_core'
require 'ajaxlibs/libraries/jquery'
require 'ajaxlibs/libraries/jqueryui'
require 'ajaxlibs/libraries/jrails'
require 'ajaxlibs/libraries/mootools'
require 'ajaxlibs/libraries/prototype'
require 'ajaxlibs/libraries/scriptaculous'
require 'ajaxlibs/libraries/swfobject'
require 'ajaxlibs/libraries/webfont.rb'
require 'ajaxlibs/includes_helper'

ActionView::Base.send(:include, Ajaxlibs::IncludesHelper) if Object.const_defined?(:ActionView)